# Start from the official Airflow image
FROM apache/airflow:2.5.1

# Switch to root user to install additional dependencies
USER root

# Install additional system dependencies (if needed)
RUN apt-get update && apt-get install -y \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Switch to airflow user
USER airflow

# Install Python dependencies
# Add any additional Python packages your project requires
RUN pip install --no-cache-dir \
    faker \
    psycopg2-binary \
    pandas

# Copy your Airflow configuration and DAGs
# Replace `/path/to/your/dags` with the local path to your DAGs folder
COPY ./dags /home/lucas-ezequiel/Documents/airflow/SBU/docker_airflow/dags

# Optional: Copy plugins, requirements, or other project files
# Replace `/path/to/your/plugins` with the local path to your plugins folder
COPY ./plugins /opt/airflow/plugins

# Set Airflow environment variables
ENV AIRFLOW_HOME=/opt/airflow

# Expose the webserver port
EXPOSE 8080

# Set the entrypoint for Airflow
ENTRYPOINT ["docker-entrypoint.sh"]

# Default command to start Airflow
CMD ["webserver"]
